name: Python test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          pip install -r requirements-dev.lock
      - name: Lint with ruff
        run: |
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          ruff --format=github --target-version=py37 .
      - name: Test with pytest
        run: |
          pytest
